# Generated by Django 5.2.11 on 2026-02-10 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('unit', models.CharField(default='un', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_branch', models.CharField(choices=[('AUSTIN', 'Austin (Base)'), ('QUEIMADOS', 'Queimados (Filial)')], default='QUEIMADOS', max_length=20)),
                ('to_branch', models.CharField(choices=[('AUSTIN', 'Austin (Base)'), ('QUEIMADOS', 'Queimados (Filial)')], default='AUSTIN', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado para Austin'), ('PICKING', 'Em separação'), ('DISPATCHED', 'Despachado/Enviado'), ('RECEIVED', 'Recebido (confirmado)'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picking_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes_from_austin', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('picking_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_picking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.PositiveIntegerField()),
                ('qty_sent', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.transferorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
