# Generated by Django 5.2.11 on 2026-02-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
