# Generated by Django 5.2.11 on 2026-02-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderlog_options_alter_orderlog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferorder',
            options={'ordering': ['-created_at']},
        ),
    ]
