# Generated by Django 5.2.11 on 2026-02-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transferorder_options_alter_orderlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
