# Generated by Django 5.2.11 on 2026-03-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_sku_alter_transferorderitem_qty_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferorderitem',
            name='qty_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='core.transferorder')),
            ],
        ),
        migrations.CreateModel(
            name='DespachoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sent_now', models.PositiveIntegerField()),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.despacho')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transferorderitem')),
            ],
        ),
    ]
