# Generated by Django 5.2.11 on 2026-03-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_despacho_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='is_complementar',
            field=models.BooleanField(default=False),
        ),
    ]
